shared:
  settings:
    email:
      addresses: [kraune@yahooinc.com]
      statuses: [SUCCESS, FAILURE]

jobs:
  link-checker-documentation:
    requires: [~pr, ~commit]
    image: ruby:2.6
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-deps: |
          gem install bundler
      - check-links: |
          export LANG=C.UTF-8
          bundle install
          bundle exec jekyll build
          find _site/en _site/documentation -name \*.html | \
            xargs grep -l "Click here if you are not redirected." | xargs rm
          bundle exec htmlproofer \
            --assume-extension \
            --check-html \
            --file-ignore '/playground/index.html/' \
            --typhoeus-config '{"connecttimeout": 10, "timeout": 30}' \
            --http-status-ignore "429" \
            _site

  verify-guides:
    requires: [~commit]
    secrets:
      - VESPA_TEAM_API_KEY
    image: vespaengine/vespa-pipeline
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-deps: |
          source /etc/profile.d/jdk-env.sh
          export PATH="$JAVA_HOME/bin:$PATH"
          yum install -y python36-pip
          pip3 install -qqq --upgrade pip
          pip3 install -qqq -r test/requirements.txt --user
          yum install -y --setopt=skip_missing_names_on_install=False unzip openssl yum-utils
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install -y --setopt=skip_missing_names_on_install=False docker-ce docker-ce-cli containerd.io docker-compose
          export VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")')
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/
      - run-tests: |
          export VESPA_TEAM_API_KEY
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config.yml

  verify-guides-large:
    requires: [~commit]
    sourcePaths: ["en/tutorials/"]
    secrets:
      - VESPA_TEAM_API_KEY
    image: vespaengine/vespa-pipeline
    environment:
      USER_SHELL_BIN: bash
    annotations:
      screwdriver.cd/cpu: HIGH
      screwdriver.cd/ram: HIGH
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: TURBO
      screwdriver.cd/dockerRam: TURBO
      screwdriver.cd/timeout: 180
      screwdriver.cd/buildPeriodically: H H(0-5) * * 1-5 # some time between 12:00 AM UTC (midnight) to 5:59 AM UTC Mon-Fri
    steps:
      - install-deps: |
          source /etc/profile.d/jdk-env.sh
          export PATH="$JAVA_HOME/bin:$PATH"
          yum install -y python36-pip
          pip3 install -qqq --upgrade pip
          pip3 install -qqq -r test/requirements.txt --user
          yum install -y --setopt=skip_missing_names_on_install=False unzip openssl yum-utils
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install -y --setopt=skip_missing_names_on_install=False docker-ce docker-ce-cli containerd.io docker-compose
          export VESPA_CLI_VERSION=$(curl -fsSL https://api.github.com/repos/vespa-engine/vespa/releases/latest | grep -Po '"tag_name": "v\K.*?(?=")')
          curl -fsSL https://github.com/vespa-engine/vespa/releases/download/v${VESPA_CLI_VERSION}/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64.tar.gz | tar -zxf - -C /opt
          ln -sf /opt/vespa-cli_${VESPA_CLI_VERSION}_linux_amd64/bin/vespa /usr/local/bin/
      - run-tests: |
          export VESPA_TEAM_API_KEY
          cd $SD_DIND_SHARE_PATH
          $SD_SOURCE_DIR/test/test.py -c $SD_SOURCE_DIR/test/_test_config-large.yml
